apiVersion: apps/v1
kind: Deployment
metadata:
  {{- if .Values.ui.annotations }}
  annotations: {{ toYaml .Values.ui.annotations | nindent 4 }}
  {{- end}}
  labels:
    app: {{ template "cp-schema-registry.fullname" . }}
    {{- if .Values.ui.labels }}
{{ toYaml .Values.ui.labels | indent 4}}
    {{- end}}
  name: {{ template "cp-schema-registry.fullname" . }}-ui
spec:
  replicas: {{ .Values.ui.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "cp-schema-registry.fullname" . }}
      service: schema-registry-ui
  template:
    metadata:
      {{- if .Values.ui.annotations }}
      annotations: {{ toYaml .Values.ui.annotations | nindent 8 }}
      {{- end }}
      labels:
        app: {{ template "cp-schema-registry.fullname" . }}
        service: schema-registry-ui
        {{- if .Values.ui.labels }}
{{ toYaml .Values.ui.labels | indent 8}}
        {{- end}}
    spec:
      {{- if .Values.securityContext }}
      securityContext: {{ toYaml .Values.securityContext | nindent 8 }}
      {{- end}}
      containers:
        - env:
          - name: SCHEMAREGISTRY_URL
            value: {{ template  "cp-schema-registry.connectUrlValue" . }}
          image: eu.gcr.io/bbc-registry/schema-registry-ui:ui_0.9.5_caddy_v2.6.4_bbc_6
          imagePullPolicy: IfNotPresent
          name: ui
          ports:
            - containerPort: 8000
              protocol: TCP
          resources: {{ toYaml .Values.ui.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  {{- if .Values.ui.annotations }}
  annotations: {{ toYaml .Values.ui.annotations | nindent 4 }}
  {{- end}}
  labels:
    app: {{ template "cp-schema-registry.fullname" . }}
    {{- if .Values.ui.labels }}
{{ toYaml .Values.ui.labels | indent 4 }}
    {{- end}}
  name: {{ template "cp-schema-registry.fullname" . }}-ui
spec:
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: {{ template "cp-schema-registry.fullname" . }}
    service: schema-registry-ui
  type: ClusterIP
