{{- if .Values.global.kafka.ssl.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cp-schema-registry.fullname" . }}-ssl-secret
  labels:
    app: {{ template "cp-schema-registry.name" . }}
    chart: {{ template "cp-schema-registry.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  kafka.client.truststore.jks: |-
{{- $path := printf "certs/%s" .Values.global.kafka.ssl.client.truststoreFile }}
{{ .Files.Get $path | b64enc | indent 4 }}
stringData:
  truststore_credentials: {{ .Values.global.kafka.ssl.client.truststorePassword }}
{{- end }}