{{- if .Values.ssl.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cp-kafka.ssl.secretName" . }}
  labels:
    app: {{ template "cp-schema-registry.name" . }}
    chart: {{ template "cp-schema-registry.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  kafka.client.truststore.jks: |-
{{- $path := printf "certs/%s" .Values.ssl.client.truststoreFile }}
{{ .Files.Get $path | b64enc | indent 4 }}
  kafka.client.keystore.jks: |-
{{- $path := printf "certs/%s" .Values.ssl.client.keystoreFile }}
{{ .Files.Get $path | b64enc | indent 4 }}
stringData:
  client.truststore.password: {{ .Values.ssl.client.truststorePassword }}
  client.keystore.password: {{ .Values.ssl.client.keystorePassword }}
  client.key.password: {{ .Values.ssl.client.keyPassword }}
{{- end }}