{{- if .Values.ssl.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cp-kafka.ssl.secretName" . }}
  labels:
    app: {{ template "cp-kafka.name" . }}
    chart: {{ template "cp-kafka.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{ .Values.ssl.broker.truststoreFile }}: |
{{- $path := printf "certs/%s" .Values.ssl.broker.truststoreFile }}
{{ .Files.Get $path | b64enc | indent 4 }}
  {{ .Values.ssl.broker.keystoreFile }}: |
{{- $path := printf "certs/%s" .Values.ssl.broker.keystoreFile }}
{{ .Files.Get $path | b64enc | indent 4 }}
stringData:
  broker.keystore.password: {{ template "cp-kafka.ssl.broker.keystorePassword" . }}
  broker.key.password: {{ template "cp-kafka.ssl.broker.keyPassword" . }}
  broker.truststore.password: {{ template "cp-kafka.ssl.broker.truststorePassword" . }}
{{- end }}