apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "cp-kafka-connect.fullname" . }}-plugins
spec:
  accessModes: {{ .Values.pluginVolume.accessModes }}
  storageClassName: {{ .Values.pluginVolume.storageClass }}
  resources:
    requests:
      storage: {{ .Values.pluginVolume.size }}