{{- if and .Values.prometheus.jmx.enabled .Values.prometheus.jmx.serviceMonitor }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "cp-zookeeper.fullname" . }}-metrics
  labels:
    app: {{ template "cp-zookeeper.name" . }}
    chart: {{ template "cp-zookeeper.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: metrics
spec:
  ports:
    - port: {{ .Values.prometheus.jmx.port }}
      name: metrics
  selector:
    app: {{ template "cp-zookeeper.name" . }}
    release: {{ .Release.Name }}
{{- end }}
