apiVersion: v1
kind: Service
metadata:
  name: {{ template "cp-zookeeper.fullname" . }}
  labels:
    app: {{ template "cp-zookeeper.name" . }}
    chart: {{ template "cp-zookeeper.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.serviceType }}
  ports:
    - port: {{ .Values.clientPort }}
      name: client
  selector:
    app: {{ template "cp-zookeeper.name" . }}
    release: {{ .Release.Name }}